# SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause

obj-$(CONFIG_PHY_APPLE_ATC)		+= phy-apple-atc.o
phy-apple-atc-y			:= atc.o

obj-$(CONFIG_PHY_APPLE_AUSB)		+= phy-apple-ausb.o
phy-apple-ausb-y			:= ausb.o
